// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyClE8kS2CR7ccmWLtmt4GdYPc_Z2dM7q58',
//     appId: '1:342439789580:web:18b49f3c69bd176e251a29',
//     messagingSenderId: '342439789580',
//     projectId: 'rentloapp-aad3f',
//     authDomain: 'rentloapp-aad3f.firebaseapp.com',
//     databaseURL: 'https://rentloapp-aad3f-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'rentloapp-aad3f.appspot.com',
//     measurementId: 'G-CL8DL4MD57',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAhKUhvS9b1UACwSO87b0mL7sHdRnC3UWQ',
//     appId: '1:342439789580:android:9ebee13b0ee49c3e251a29',
//     messagingSenderId: '342439789580',
//     projectId: 'rentloapp-aad3f',
//     databaseURL: 'https://rentloapp-aad3f-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'rentloapp-aad3f.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyD8w4BHDA8aMVijTIKe0MteNANJ8H9H4RQ',
//     appId: '1:342439789580:ios:7d54e7dfbf3f9fc0251a29',
//     messagingSenderId: '342439789580',
//     projectId: 'rentloapp-aad3f',
//     databaseURL: 'https://rentloapp-aad3f-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'rentloapp-aad3f.appspot.com',
//     androidClientId: '342439789580-3j823qp34i067r8k73mkebvqfltrpjjb.apps.googleusercontent.com',
//     iosClientId: '342439789580-segqtd16d4a6sh7erdqa08l3tj491o43.apps.googleusercontent.com',
//     iosBundleId: 'com.example.rentloapp',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyD8w4BHDA8aMVijTIKe0MteNANJ8H9H4RQ',
//     appId: '1:342439789580:ios:7d54e7dfbf3f9fc0251a29',
//     messagingSenderId: '342439789580',
//     projectId: 'rentloapp-aad3f',
//     databaseURL: 'https://rentloapp-aad3f-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'rentloapp-aad3f.appspot.com',
//     androidClientId: '342439789580-3j823qp34i067r8k73mkebvqfltrpjjb.apps.googleusercontent.com',
//     iosClientId: '342439789580-segqtd16d4a6sh7erdqa08l3tj491o43.apps.googleusercontent.com',
//     iosBundleId: 'com.example.rentloapp',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBeiKfInbD8d7UEZn3XuaT4af-MyA_gGds',
//     appId: '1:342439789580:web:4b32ac462d2e182e251a29',
//     messagingSenderId: '342439789580',
//     projectId: 'rentloapp-aad3f',
//     authDomain: 'rentloapp-aad3f.firebaseapp.com',
//     databaseURL: 'https://rentloapp-aad3f-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'rentloapp-aad3f.appspot.com',
//     measurementId: 'G-941W8WFGM8',
//   );
//
// }